/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Studies */
        get: operations["list_studies_api_v1_studies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Approval */
        post: operations["record_approval_api_v1_studies__study_id__approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/claims/{claim_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_studies__study_id__claims__claim_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/data-validation-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Data Validation */
        post: operations["run_data_validation_api_v1_studies__study_id__data_validation_packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Package */
        post: operations["export_package_api_v1_studies__study_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/exports/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_api_v1_studies__study_id__exports__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/pinned-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze Run */
        post: operations["freeze_run_api_v1_studies__study_id__pinned_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/section-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Section */
        post: operations["run_section_api_v1_studies__study_id__section_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/section-runs/{run_id}/cross-section-queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Cross Section */
        post: operations["query_cross_section_api_v1_studies__study_id__section_runs__run_id__cross_section_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/section-runs/{run_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Candidate */
        post: operations["evaluate_candidate_api_v1_studies__study_id__section_runs__run_id__evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/validation-results/{result_id}/dispositions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Disposition */
        post: operations["record_disposition_api_v1_studies__study_id__validation_results__result_id__dispositions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/validation-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Validation */
        post: operations["run_validation_api_v1_studies__study_id__validation_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_studies__study_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Approval */
        Approval: {
            /** Approval Id */
            approval_id: string;
            /** Meaning */
            meaning: string;
            /** Reviewer */
            reviewer: string;
            role: components["schemas"]["ApprovalRole"];
            /** Timestamp */
            timestamp: string;
        };
        /** ApprovalCommand */
        ApprovalCommand: {
            /** Meaning */
            meaning: string;
            /** Reviewer */
            reviewer: string;
            role: components["schemas"]["ApprovalRole"];
        };
        /**
         * ApprovalRole
         * @enum {string}
         */
        ApprovalRole: "pathologist" | "peer_reviewer" | "qau" | "study_director";
        /** AssembledSection */
        AssembledSection: {
            /** Blocks */
            blocks: components["schemas"]["ReportBlock"][];
            /** Fields */
            fields: components["schemas"]["ReportFieldTemplate"][];
            /** Required Field Count */
            required_field_count: number;
            /** Section Id */
            section_id: string;
            status: components["schemas"]["SectionStatus"];
            /** Title */
            title: string;
        };
        /** CandidateEvaluation */
        CandidateEvaluation: {
            /** Candidate Hash */
            candidate_hash: string;
            /** Candidate Id */
            candidate_id: string;
            /** Evaluation Id */
            evaluation_id: string;
            hashes: components["schemas"]["CandidateEvaluationHashes"];
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
            next_attempt_decision: components["schemas"]["NextAttemptDecision"];
            provenance_receipt: components["schemas"]["ProvenanceReceipt"];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.candidate-evaluation/v1";
            /** Section Package Id */
            section_package_id: string;
            study_output_evaluation_receipt: components["schemas"]["StudyOutputEvaluationReceipt"];
            template_conformance_receipt: components["schemas"]["TemplateConformanceReceipt"];
        };
        /** CandidateEvaluationCommand */
        CandidateEvaluationCommand: {
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** CandidateEvaluationHashes */
        CandidateEvaluationHashes: {
            /** Candidate */
            candidate: string;
            /** Evaluation */
            evaluation: string;
            /** Provenance */
            provenance: string;
            /** Study Output Evaluation */
            study_output_evaluation: string;
            /** Template Conformance */
            template_conformance: string;
        };
        /** Claim */
        Claim: {
            /** Claim Id */
            claim_id: string;
            /** Claim Type */
            claim_type?: string | null;
            /** Executor Id */
            executor_id?: string | null;
            /** Executor Version */
            executor_version?: string | null;
            /** Field Id */
            field_id: string;
            /** Grain */
            grain: string;
            /** Grain Key */
            grain_key?: {
                [key: string]: string;
            };
            /** Package Id */
            package_id?: string | null;
            /** Package Version */
            package_version?: string | null;
            /** Rule Versions */
            rule_versions?: {
                [key: string]: string;
            };
            /** Section Id */
            section_id: string;
            /** Source Hashes */
            source_hashes?: string[];
            status: components["schemas"]["ClaimStatus"];
            /** Transform Id */
            transform_id?: string | null;
            /** Transform Version */
            transform_version?: string | null;
            /** Unit */
            unit: string;
            /** Value */
            value: number | null;
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "pending" | "validated" | "needs_review" | "approved";
        /** CrossSectionQueryCommand */
        CrossSectionQueryCommand: {
            /** Artifact Ids */
            artifact_ids: string[];
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** CrossSectionQueryReceipt */
        CrossSectionQueryReceipt: {
            /** Message */
            message?: string | null;
            /** Query Id */
            query_id: string;
            /** Rejected Artifact Ids */
            rejected_artifact_ids: string[];
            /** Requested Artifact Ids */
            requested_artifact_ids: string[];
            /** Returned */
            returned: components["schemas"]["CrossSectionReturnedArtifact"][];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.cross-section-query-receipt/v1";
            /** Section Package Id */
            section_package_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "returned" | "rejected";
        };
        /** CrossSectionReturnedArtifact */
        CrossSectionReturnedArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Hash */
            hash: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fact" | "claim" | "section_draft";
        };
        /** DataValidationCommand */
        DataValidationCommand: {
            /** Actor */
            actor: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Package Id
             * @default validation.body_weight
             */
            package_id: string;
        };
        /** DataValidationExecution */
        DataValidationExecution: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            event: components["schemas"]["WorkflowEvent"];
            /** Provenance Edges */
            provenance_edges: components["schemas"]["ProvenanceEdge"][];
            receipt: components["schemas"]["DataValidationReceipt"];
            /** Results */
            results: components["schemas"]["DataValidationRuleResult"][];
            /** Section References */
            section_references: components["schemas"]["SectionClaimReference"][];
        };
        /** DataValidationReceipt */
        DataValidationReceipt: {
            /** Claim Ids */
            claim_ids: string[];
            /** Event Id */
            event_id: string;
            /** Executor Hash */
            executor_hash: string;
            /** Executor Id */
            executor_id: string;
            /** Executor Version */
            executor_version: string;
            /** Governed Versions */
            governed_versions: {
                [key: string]: string;
            };
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Node Id */
            node_id: string;
            /** Package Hash */
            package_hash: string;
            /** Package Id */
            package_id: string;
            /** Package Version */
            package_version: string;
            /** Receipt Id */
            receipt_id: string;
            /** Result Ids */
            result_ids: string[];
            /** Rule Bundle Id */
            rule_bundle_id: string;
            /** Rule Ids */
            rule_ids: string[];
            /** Run Id */
            run_id: string;
            /** Source Artifact Id */
            source_artifact_id: string;
            /** Source Hash */
            source_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "blocked";
        };
        /** DataValidationRuleResult */
        DataValidationRuleResult: {
            /**
             * Enforcement Class
             * @enum {string}
             */
            enforcement_class: "hard_blocker" | "review_required" | "warning";
            /** Evidence Ids */
            evidence_ids: string[];
            /** Executor Id */
            executor_id: string;
            /** Message */
            message: string;
            /** Package Id */
            package_id: string;
            /** Result Id */
            result_id: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version: string;
            /** Scope Id */
            scope_id: string;
            status: components["schemas"]["ValidationStatus"];
            /** Waivable */
            waivable: boolean;
        };
        /** DispositionCommand */
        DispositionCommand: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "corrected" | "explained_in_nsdrg" | "approved_exception";
            /** Reason */
            reason: string;
            /** Reviewer */
            reviewer: string;
        };
        /**
         * DispositionDecision
         * @enum {string}
         */
        DispositionDecision: "open" | "corrected" | "explained_in_nsdrg" | "approved_exception" | "rejected";
        /** DoseGroup */
        DoseGroup: {
            /** Dose */
            dose: number;
            /** Dose Unit */
            dose_unit: string;
            /** Group Id */
            group_id: string;
            /** Label */
            label: string;
            /** Planned N Per Sex */
            planned_n_per_sex: number;
            /** Sexes */
            sexes: ("M" | "F")[];
            /** Study Id */
            study_id: string;
        };
        /** EvidenceChain */
        EvidenceChain: {
            claim: components["schemas"]["Claim"];
            /** Exact Match */
            exact_match: boolean | null;
            /** Lineage */
            lineage?: components["schemas"]["ProvenanceEdge"][];
            /** Recomputed Value */
            recomputed_value: number | null;
            /** Report Text */
            report_text: string;
            /** Rule Versions */
            rule_versions?: {
                [key: string]: string;
            };
            /** Source Hashes */
            source_hashes?: string[];
            /** Sources */
            sources: components["schemas"]["SourceRecord"][];
            /** Transform Id */
            transform_id: string | null;
            /** Transform Version */
            transform_version?: string | null;
            /** Validations */
            validations: components["schemas"]["ValidationResult"][];
        };
        /** ExportArtifact */
        ExportArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Checksum */
            checksum: string | null;
            /** Kind */
            kind: string;
            /** Path */
            path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "exported";
        };
        /** ExportCommand */
        ExportCommand: {
            /** Actor */
            actor: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** ExportReceipt */
        ExportReceipt: {
            /** Artifacts */
            artifacts: components["schemas"]["ExportArtifact"][];
            /** Exported At */
            exported_at: string;
            /** Idempotent Replay */
            idempotent_replay: boolean;
            /**
             * Status
             * @constant
             */
            status: "exported";
            /** Study Id */
            study_id: string;
        };
        /** FreezeRunCommand */
        FreezeRunCommand: {
            /** Actor */
            actor: string;
            /** Idempotency Key */
            idempotency_key: string;
            supersession?: components["schemas"]["SupersessionRef"] | null;
        };
        /** GateDecision */
        GateDecision: {
            /** Blocking Result Ids */
            blocking_result_ids: string[];
            /** Decided At */
            decided_at: string;
            /** Gate Id */
            gate_id: string;
            /**
             * Gate Type
             * @enum {string}
             */
            gate_type: "section" | "release";
            status: components["schemas"]["GateStatus"];
        };
        /**
         * GateStatus
         * @enum {string}
         */
        GateStatus: "blocked" | "ready_for_review" | "ready_for_signature" | "ready_for_export" | "exported";
        /** GovernedArtifact */
        GovernedArtifact: {
            /** Artifact Id */
            artifact_id: string;
            /** Content Hash */
            content_hash: string;
            /** Kind */
            kind: string;
            /** Path */
            path: string;
            /** Version */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ManifestEntry */
        ManifestEntry: {
            /** Artifact Id */
            artifact_id: string;
            /** Authority Tier */
            authority_tier: number;
            /** Authorized By */
            authorized_by: string;
            /** Checksum */
            checksum: string;
            /** Kind */
            kind: string;
            /** Locked */
            locked: boolean;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** NextAttemptDecision */
        NextAttemptDecision: {
            /**
             * Action
             * @enum {string}
             */
            action: "retry" | "stop_for_review" | "hold";
            /** Attempt */
            attempt: number;
            /** Blocking Receipt Ids */
            blocking_receipt_ids: string[];
            /**
             * Max Attempts
             * @constant
             */
            max_attempts: 3;
            /** Reasons */
            reasons: string[];
        };
        /** PinnedRun */
        PinnedRun: {
            /** Created At */
            created_at: string;
            /** Event History */
            event_history: components["schemas"]["WorkflowEvent"][];
            /** Governed Inputs */
            governed_inputs: components["schemas"]["GovernedArtifact"][];
            /** Manifest Hash */
            manifest_hash: string;
            /** Predecessor Run Id */
            predecessor_run_id?: string | null;
            receipt: components["schemas"]["RunReceipt"];
            /** Run Id */
            run_id: string;
            run_plan: components["schemas"]["RunPlan"];
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "needs_review";
            /** Study Id */
            study_id: string;
            study_type_resolution: components["schemas"]["StudyTypeResolution"];
            /** Supersession Reason */
            supersession_reason?: string | null;
        };
        /** PlannerCapability */
        PlannerCapability: {
            /** Available */
            available: boolean;
            /** Detail */
            detail: string;
            /** Label */
            label: string;
            mode: components["schemas"]["PlannerMode"];
        };
        /**
         * PlannerMode
         * @enum {string}
         */
        PlannerMode: "fixture" | "openai_compatible";
        /** PlanningEvidence */
        PlanningEvidence: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Subject */
            subject: string;
        };
        /** ProvenanceBinding */
        ProvenanceBinding: {
            /** Artifact Hash */
            artifact_hash: string;
            /** Claim Hash */
            claim_hash: string;
            /** Claim Id */
            claim_id: string;
            /** Location */
            location: string;
            /** Text */
            text: string;
        };
        /** ProvenanceBlocker */
        ProvenanceBlocker: {
            /** Code */
            code: string;
            /** Location */
            location: string;
            /** Message */
            message: string;
            /** Text */
            text: string;
        };
        /** ProvenanceEdge */
        ProvenanceEdge: {
            /** Authority Tier */
            authority_tier: number;
            /** Claim Id */
            claim_id: string;
            /** Edge Id */
            edge_id: string;
            /** Source Hash */
            source_hash?: string | null;
            /** Source Pointer */
            source_pointer: string;
            /** Source Record Id */
            source_record_id: string;
            /** Transform Id */
            transform_id: string;
            /** Transform Version */
            transform_version?: string | null;
        };
        /** ProvenanceReceipt */
        ProvenanceReceipt: {
            /** Bindings */
            bindings: components["schemas"]["ProvenanceBinding"][];
            /** Blockers */
            blockers: components["schemas"]["ProvenanceBlocker"][];
            /** Candidate Hash */
            candidate_hash: string;
            /** Candidate Id */
            candidate_id: string;
            /**
             * Enforcement Class
             * @constant
             */
            enforcement_class: "hard_blocker";
            /** Receipt Id */
            receipt_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.provenance-receipt/v1";
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "blocked";
            /**
             * Waivable
             * @constant
             */
            waivable: false;
        };
        /** RegulatoryReference */
        RegulatoryReference: {
            /**
             * Authority
             * @enum {string}
             */
            authority: "regulation" | "guidance" | "standard" | "test_guideline";
            /** Binding */
            binding: boolean;
            /** Citation */
            citation: string;
            /** Reference Id */
            reference_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** ReportAssembly */
        ReportAssembly: {
            /** Sections */
            sections: components["schemas"]["AssembledSection"][];
            template: components["schemas"]["ReportTemplate"];
        };
        /** ReportBlock */
        ReportBlock: {
            /** Block Id */
            block_id: string;
            /** Claim Id */
            claim_id?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "paragraph" | "claim" | "review_marker";
            /**
             * Provenance Count
             * @default 0
             */
            provenance_count: number;
            /** Text */
            text: string;
        };
        /** ReportFieldTemplate */
        ReportFieldTemplate: {
            /** Expected Grain */
            expected_grain: string;
            /** Field Id */
            field_id: string;
            /** Human Judgment */
            human_judgment: boolean;
            /** Label */
            label: string;
            /** Location */
            location?: string | null;
            /** Regulatory Reference Ids */
            regulatory_reference_ids: string[];
            /** Required */
            required: boolean;
            /** Source Expectation */
            source_expectation: string;
            style_constraints?: components["schemas"]["TemplateStyleConstraints"] | null;
            table_shape?: components["schemas"]["TemplateTableShape"] | null;
            /** Unit */
            unit?: string | null;
        };
        /** ReportSectionTemplate */
        ReportSectionTemplate: {
            /** Fields */
            fields: components["schemas"]["ReportFieldTemplate"][];
            /** Purpose */
            purpose: string;
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
        };
        /** ReportTemplate */
        ReportTemplate: {
            /** Ctd Location */
            ctd_location: string;
            /** Disclaimer */
            disclaimer: string;
            /** Name */
            name: string;
            /** References */
            references: components["schemas"]["RegulatoryReference"][];
            /** Sections */
            sections: components["schemas"]["ReportSectionTemplate"][];
            /** Study Type Id */
            study_type_id: string;
            /** Template Id */
            template_id: string;
            /** Version */
            version: string;
        };
        /** ReviewDisposition */
        ReviewDisposition: {
            /** Artifact Id */
            artifact_id?: string | null;
            decision: components["schemas"]["DispositionDecision"];
            /** Disposition Id */
            disposition_id: string;
            /** Reason */
            reason: string | null;
            /** Result Id */
            result_id: string;
            /** Reviewer */
            reviewer: string | null;
            /** Timestamp */
            timestamp: string | null;
        };
        /** RunPlan */
        RunPlan: {
            /** Created At */
            created_at: string;
            /** Fingerprint */
            fingerprint: string;
            /** Governed Versions */
            governed_versions: {
                [key: string]: string;
            };
            /** Manifest Hash */
            manifest_hash: string;
            /** Nodes */
            nodes: components["schemas"]["RunPlanNode"][];
            /** Run Id */
            run_id: string;
            /** Run Plan Id */
            run_plan_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.run-plan/v1";
            /** Version */
            version: number;
        };
        /** RunPlanNode */
        RunPlanNode: {
            /** Depends On */
            depends_on: string[];
            /** Evidence */
            evidence: components["schemas"]["PlanningEvidence"][];
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Node Id */
            node_id: string;
            /**
             * Node Type
             * @enum {string}
             */
            node_type: "parse" | "study_type_resolution" | "data_validation" | "template_contract" | "section_agent" | "provenance" | "study_output_evaluation" | "template_conformance" | "section_promotion" | "review_scaffold";
            /** Package Id */
            package_id?: string | null;
            /** Package Version */
            package_version?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "blocked";
        };
        /** RunReceipt */
        RunReceipt: {
            /** Event Id */
            event_id: string;
            /** Governed Inputs Fingerprint */
            governed_inputs_fingerprint: string;
            /** Manifest Hash */
            manifest_hash: string;
            /** Receipt Id */
            receipt_id: string;
            /** Run Id */
            run_id: string;
            /** Run Plan Fingerprint */
            run_plan_fingerprint: string;
        };
        /** SectionClaimReference */
        SectionClaimReference: {
            /** Claim Id */
            claim_id: string;
            /** Executor Receipt Id */
            executor_receipt_id: string;
            /** Section Id */
            section_id: string;
            /** Section Package Id */
            section_package_id: string;
            /** Title */
            title: string;
        };
        /** SectionDraftCandidate */
        SectionDraftCandidate: {
            /** Agent Receipt */
            agent_receipt: {
                [key: string]: string;
            };
            /** Attempt */
            attempt: number;
            /** Candidate Id */
            candidate_id: string;
            /** Content Blocks */
            content_blocks: {
                [key: string]: unknown;
            }[];
            /** Drafting Cycle Id */
            drafting_cycle_id: string;
            /** Executor Receipt Ids */
            executor_receipt_ids: string[];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.section-draft-candidate/v1";
            /** Section Id */
            section_id: string;
            /** Section Package Id */
            section_package_id: string;
            /** Section Package Version */
            section_package_version: string;
            /**
             * Status
             * @constant
             */
            status: "section_draft_candidate";
            /** Validated Claim Ids */
            validated_claim_ids: string[];
        };
        /** SectionImpactSet */
        SectionImpactSet: {
            /** Direct */
            direct: string[];
            /** Origin Section Package Id */
            origin_section_package_id: string;
            /** Transitive */
            transitive: string[];
        };
        /** SectionRunCommand */
        SectionRunCommand: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Section Package Id */
            section_package_id: string;
        };
        /** SectionRunEligibility */
        SectionRunEligibility: {
            /** Eligible */
            eligible: boolean;
            /** Gate Results */
            gate_results: components["schemas"]["TemplateContractGateResult"][];
            impact_set: components["schemas"]["SectionImpactSet"];
            /** Reasons */
            reasons: string[];
            /** Section Package Id */
            section_package_id: string;
        };
        /** SectionRunReceipt */
        SectionRunReceipt: {
            /**
             * Agent Runtime
             * @constant
             */
            agent_runtime: "codex_sdk";
            /** Candidate Hash */
            candidate_hash: string;
            /** Candidate Id */
            candidate_id: string;
            /** Codex Thread Id */
            codex_thread_id: string;
            /** Envelope Hash */
            envelope_hash: string;
            /**
             * Idempotent Replay
             * @default false
             */
            idempotent_replay: boolean;
            /** Review Scaffold Revision */
            review_scaffold_revision: number;
            /** Run Id */
            run_id: string;
            /** Section Id */
            section_id: string;
            /** Section Package Id */
            section_package_id: string;
            /** Skill Hash */
            skill_hash: string;
            /**
             * Skill Name
             * @constant
             */
            skill_name: "helix-section-agent";
            /**
             * Status
             * @constant
             */
            status: "candidate_recorded";
        };
        /**
         * SectionStatus
         * @enum {string}
         */
        SectionStatus: "validated" | "needs_review" | "reviewed";
        /** SourceRecord */
        SourceRecord: {
            /** Attributes */
            attributes: {
                [key: string]: string | number | null;
            };
            /** Domain */
            domain: string;
            /** Grain */
            grain: string;
            /** Record Id */
            record_id: string;
            /** Source Pointer */
            source_pointer: string;
            /** Unit */
            unit: string | null;
            /** Value */
            value: number | string;
        };
        /** Stage */
        Stage: {
            /** Boundary */
            boundary: string;
            /** Checks */
            checks: string[];
            /** Input Detail */
            input_detail: string;
            /** Input Title */
            input_title: string;
            /** Name */
            name: string;
            /** Output Detail */
            output_detail: string;
            /** Output Title */
            output_title: string;
            /**
             * Owner
             * @enum {string}
             */
            owner: "agent" | "human" | "hybrid";
            /** Stage Id */
            stage_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "current" | "blocked" | "pending";
            /** Summary */
            summary: string;
        };
        /** StoredSectionRun */
        StoredSectionRun: {
            candidate: components["schemas"]["SectionDraftCandidate"];
            /** Envelope */
            envelope: {
                [key: string]: unknown;
            };
            receipt: components["schemas"]["SectionRunReceipt"];
            /** Review Scaffold */
            review_scaffold: {
                [key: string]: unknown;
            };
        };
        /** Study */
        Study: {
            /** Dose Groups */
            dose_groups: components["schemas"]["DoseGroup"][];
            /** Duration Days */
            duration_days: number;
            /** Protocol Version */
            protocol_version: string;
            /** Route */
            route: string;
            /** Species */
            species: string;
            /** Study Id */
            study_id: string;
            /** Study Start */
            study_start: string;
            /** Study Type Id */
            study_type_id: string;
        };
        /** StudyListItem */
        StudyListItem: {
            /** Label */
            label: string;
            release_status: components["schemas"]["GateStatus"];
            /** Study Id */
            study_id: string;
            /** Study Type Id */
            study_type_id: string;
            /** Title */
            title: string;
            /** Workflow State */
            workflow_state: string;
        };
        /** StudyOutputAssertionResult */
        StudyOutputAssertionResult: {
            /** Assertion */
            assertion: string;
            /** Message */
            message: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed";
        };
        /** StudyOutputEvaluationReceipt */
        StudyOutputEvaluationReceipt: {
            /** Candidate Hash */
            candidate_hash: string;
            /** Candidate Id */
            candidate_id: string;
            /**
             * Enforcement Class
             * @constant
             */
            enforcement_class: "review_required";
            /** Receipt Id */
            receipt_id: string;
            /** Results */
            results: components["schemas"]["StudyOutputAssertionResult"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.study-output-evaluation-receipt/v1";
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed";
            /** Suite Hash */
            suite_hash: string;
            /** Suite Id */
            suite_id: string;
            /** Suite Version */
            suite_version: string;
            /** Waivable */
            waivable: boolean;
        };
        /** StudyTypeResolution */
        StudyTypeResolution: {
            /** Evidence */
            evidence: components["schemas"]["PlanningEvidence"][];
            /** Mapping Hash */
            mapping_hash: string;
            /** Mapping Version */
            mapping_version: string;
            /** Protocol Fields */
            protocol_fields: {
                [key: string]: string | number;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "needs_review";
            /** Study Type Id */
            study_type_id: string | null;
        };
        /** SupersessionRef */
        SupersessionRef: {
            /** Predecessor Run Id */
            predecessor_run_id: string;
            /** Reason */
            reason: string;
        };
        /** TemplateConformanceReceipt */
        TemplateConformanceReceipt: {
            /** Candidate Hash */
            candidate_hash: string;
            /** Candidate Id */
            candidate_id: string;
            /** Receipt Id */
            receipt_id: string;
            /** Results */
            results: components["schemas"]["TemplateConformanceResult"][];
            /**
             * Schema Version
             * @constant
             */
            schema_version: "helix.template-conformance-receipt/v1";
            /** Section Package Id */
            section_package_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "blocked";
        };
        /** TemplateConformanceResult */
        TemplateConformanceResult: {
            /**
             * Check Kind
             * @enum {string}
             */
            check_kind: "completeness" | "table_coverage" | "terminology" | "units" | "rounding" | "approved_language";
            /**
             * Enforcement Class
             * @constant
             */
            enforcement_class: "hard_blocker";
            /** Gate Id */
            gate_id: string;
            /** Message */
            message: string;
            /** Rule Id */
            rule_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "blocked";
            /**
             * Waivable
             * @constant
             */
            waivable: false;
        };
        /** TemplateContractGateResult */
        TemplateContractGateResult: {
            /**
             * Check Kind
             * @enum {string}
             */
            check_kind: "fields" | "locations" | "table_shapes" | "labels" | "units" | "style_constraints";
            /**
             * Enforcement Class
             * @constant
             */
            enforcement_class: "hard_blocker";
            /** Gate Id */
            gate_id: string;
            /** Message */
            message: string;
            /** Result Id */
            result_id: string;
            /** Section Package Id */
            section_package_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "blocked";
            /**
             * Waivable
             * @constant
             */
            waivable: false;
        };
        /** TemplateStyleConstraints */
        TemplateStyleConstraints: {
            /** Decimal Places */
            decimal_places: number;
            /** Forbidden Terms */
            forbidden_terms?: string[];
            /** Unit Display */
            unit_display: string;
        };
        /** TemplateTableShape */
        TemplateTableShape: {
            /** Column Axis */
            column_axis: string;
            /** Grain */
            grain: string;
            /** Row Axis */
            row_axis: string;
            /** Value Columns */
            value_columns: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationKind
         * @enum {string}
         */
        ValidationKind: "deterministic" | "agent_planned";
        /** ValidationRequest */
        ValidationRequest: {
            /** @default fixture */
            planner: components["schemas"]["PlannerMode"];
        };
        /** ValidationResult */
        ValidationResult: {
            /** Enforcement Class */
            enforcement_class?: ("hard_blocker" | "review_required" | "warning") | null;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Executor Id */
            executor_id?: string | null;
            /** @default deterministic */
            kind: components["schemas"]["ValidationKind"];
            /** Message */
            message: string;
            /** Package Id */
            package_id?: string | null;
            /** Result Id */
            result_id: string;
            /** Rule Id */
            rule_id: string;
            /** Rule Version */
            rule_version: string;
            /** Scope Id */
            scope_id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "blocker";
            status: components["schemas"]["ValidationStatus"];
            /** Tool Name */
            tool_name?: string | null;
            /** Waivable */
            waivable?: boolean | null;
        };
        /** ValidationRun */
        ValidationRun: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Llm Used */
            llm_used: boolean;
            planner: components["schemas"]["PlannerMode"];
            /** Planner Label */
            planner_label: string;
            /** Results */
            results: components["schemas"]["ValidationResult"][];
            /** Rule Bundle Version */
            rule_bundle_version: string;
            /** Run Id */
            run_id: string;
            /** Study Id */
            study_id: string;
        };
        /**
         * ValidationStatus
         * @enum {string}
         */
        ValidationStatus: "pass" | "warn" | "fail" | "skipped";
        /** WorkflowEvent */
        WorkflowEvent: {
            /** Actor */
            actor: string;
            /** Details */
            details?: {
                [key: string]: string | number | boolean | null;
            };
            /** Event */
            event: string;
            /** Event Id */
            event_id: string;
            /** Outcome */
            outcome: string;
            /** Timestamp */
            timestamp: string;
        };
        /** WorkspaceResponse */
        WorkspaceResponse: {
            /** Approvals */
            approvals: components["schemas"]["Approval"][];
            /** Candidate Evaluations */
            candidate_evaluations?: components["schemas"]["CandidateEvaluation"][];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Cross Section Queries */
            cross_section_queries?: components["schemas"]["CrossSectionQueryReceipt"][];
            /** Data Validation Executions */
            data_validation_executions: components["schemas"]["DataValidationExecution"][];
            /** Dispositions */
            dispositions: components["schemas"]["ReviewDisposition"][];
            /** Events */
            events: components["schemas"]["WorkflowEvent"][];
            /** Export Artifacts */
            export_artifacts: components["schemas"]["ExportArtifact"][];
            /** Label */
            label: string;
            /** Manifest */
            manifest: components["schemas"]["ManifestEntry"][];
            pinned_run: components["schemas"]["PinnedRun"] | null;
            /** Planner Capabilities */
            planner_capabilities: components["schemas"]["PlannerCapability"][];
            release_gate: components["schemas"]["GateDecision"];
            report: components["schemas"]["ReportAssembly"];
            /** Review Scaffold Revisions */
            review_scaffold_revisions?: {
                [key: string]: unknown;
            }[];
            /** Section Run Eligibility */
            section_run_eligibility: components["schemas"]["SectionRunEligibility"][];
            /** Section Runs */
            section_runs: components["schemas"]["StoredSectionRun"][];
            /** Stages */
            stages: components["schemas"]["Stage"][];
            study: components["schemas"]["Study"];
            summary: components["schemas"]["WorkspaceSummary"];
            /** Validations */
            validations: components["schemas"]["ValidationResult"][];
            /** Workflow State */
            workflow_state: string;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /** Blocker Count */
            blocker_count: number;
            /** Provenance Count */
            provenance_count: number;
            /** Record Count */
            record_count: number;
            /** Resolved Blocker Count */
            resolved_blocker_count: number;
            /** Section Count */
            section_count: number;
            /** Source Count */
            source_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_studies_api_v1_studies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyListItem"][];
                };
            };
        };
    };
    record_approval_api_v1_studies__study_id__approvals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_studies__study_id__claims__claim_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceChain"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_data_validation_api_v1_studies__study_id__data_validation_packages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DataValidationCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataValidationExecution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_package_api_v1_studies__study_id__exports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_artifact_api_v1_studies__study_id__exports__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    freeze_run_api_v1_studies__study_id__pinned_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FreezeRunCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinnedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_section_api_v1_studies__study_id__section_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionRunCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionRunReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_cross_section_api_v1_studies__study_id__section_runs__run_id__cross_section_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrossSectionQueryCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrossSectionQueryReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_candidate_api_v1_studies__study_id__section_runs__run_id__evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateEvaluationCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateEvaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_disposition_api_v1_studies__study_id__validation_results__result_id__dispositions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispositionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_validation_api_v1_studies__study_id__validation_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_studies__study_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
